import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import Header from "@/components/features/Header";
import ScrollUpButton from "@/components/atoms/ScrollUpButton";
import Footer from "@/components/features/Footer";
import AuthProvider from "@/components/AuthProvider";
import { Toaster } from "sonner";

const geistSans = Cairo({
  variable: "--cairo",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Nourborsa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        <AuthProvider>
          <ReactQueryProvider>
           
            <Header />
            {children}
            <Toaster position="top-right"/>
            <ScrollUpButton />
            <Footer />
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
