import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import Header from "@/components/features/Header";
import WhatsAppBtn from "@/components/atoms/WhatsAppBtn";
import ScrollUpButton from "@/components/atoms/ScrollUpButton";

const geistSans = Cairo({
  variable: "--cairo",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        <ReactQueryProvider>
          <Header />
          {children}
          <WhatsAppBtn phoneNumber={123456789} />
          <ScrollUpButton />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
