import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/ReactQueryProvider";

const geistSans = Cairo({
  variable: "--cairo",
  subsets: ["arabic"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        <ReactQueryProvider>
        {children}

        </ReactQueryProvider>
      </body>
    </html>
  );
}
